services:
    amy_google_checkout:
        class: Amy\GoogleCheckoutBundle\Service
        calls:
            - [setMerchantID, ["%amy_google_checkout.merchant_id%"]]
            - [setMerchantKey, ["%amy_google_checkout.merchant_key%"]]
            - [setServerType, ["%amy_google_checkout.server_type%"]]
            - [setSslCertificatePath, ["%amy_google_checkout.ssl_certificate_path%"]]
